//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimerParcial.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrimerParcial.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantón.
        /// </summary>
        internal static string canton {
            get {
                return ResourceManager.GetString("canton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casos.
        /// </summary>
        internal static string cases {
            get {
                return ResourceManager.GetString("cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string dateAdd {
            get {
                return ResourceManager.GetString("dateAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango de fechas:.
        /// </summary>
        internal static string dateSearch {
            get {
                return ResourceManager.GetString("dateSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallecidos.
        /// </summary>
        internal static string deads {
            get {
                return ResourceManager.GetString("deads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tasa de Mortalidad.
        /// </summary>
        internal static string deathrate {
            get {
                return ResourceManager.GetString("deathrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde:.
        /// </summary>
        internal static string lblsince {
            get {
                return ResourceManager.GetString("lblsince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres de estudiantes: .
        /// </summary>
        internal static string lblStudents {
            get {
                return ResourceManager.GetString("lblStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta:.
        /// </summary>
        internal static string lbluntil {
            get {
                return ResourceManager.GetString("lbluntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casos Generales.
        /// </summary>
        internal static string mnuGeneral {
            get {
                return ResourceManager.GetString("mnuGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Casos.
        /// </summary>
        internal static string mnuNewRecord {
            get {
                return ResourceManager.GetString("mnuNewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casos Específicos.
        /// </summary>
        internal static string mnuSpecific {
            get {
                return ResourceManager.GetString("mnuSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Universidad de Costa Rica.
        /// </summary>
        internal static string mnuTitle {
            get {
                return ResourceManager.GetString("mnuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Negativos.
        /// </summary>
        internal static string negatives {
            get {
                return ResourceManager.GetString("negatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Positivos.
        /// </summary>
        internal static string positives {
            get {
                return ResourceManager.GetString("positives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Positividad.
        /// </summary>
        internal static string postivityrate {
            get {
                return ResourceManager.GetString("postivityrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        internal static string province {
            get {
                return ResourceManager.GetString("province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canton de Registro.
        /// </summary>
        internal static string recordcanton {
            get {
                return ResourceManager.GetString("recordcanton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Registro.
        /// </summary>
        internal static string recorddate {
            get {
                return ResourceManager.GetString("recorddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia de Registro.
        /// </summary>
        internal static string recordprovince {
            get {
                return ResourceManager.GetString("recordprovince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperados.
        /// </summary>
        internal static string recovered {
            get {
                return ResourceManager.GetString("recovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperación.
        /// </summary>
        internal static string recoveryrate {
            get {
                return ResourceManager.GetString("recoveryrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Fallecimientos.
        /// </summary>
        internal static string totaldeaths {
            get {
                return ResourceManager.GetString("totaldeaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Negativos.
        /// </summary>
        internal static string totalnegative {
            get {
                return ResourceManager.GetString("totalnegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Positivos.
        /// </summary>
        internal static string totalpositive {
            get {
                return ResourceManager.GetString("totalpositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Recuperados.
        /// </summary>
        internal static string totalrecovered {
            get {
                return ResourceManager.GetString("totalrecovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Testeados.
        /// </summary>
        internal static string totaltested {
            get {
                return ResourceManager.GetString("totaltested", resourceCulture);
            }
        }
    }
}
